### ISSUE TITLE
How to run this in my local machine

### ISSUE THREAD

**Issue by lsatpathy** [mathew-kurian/CharacterMap#4]
Hi,
I am a novice and trying to run this in my local machine. Could you tell me the steps to run this. Your response will be very much appreciated.

Thanks

**Comment by Ouaz** [comment]
Hi,

First of all, thanks to bluejamesbond for this great tool.

@lsatpathy 

It's possible to run CharacterMap on your local machine (offline), but it requires some tweaks.

1) Download the zip archive from Github.

2) Open it and extract "CharacterMap-master" folder to your desktop.

3) Open the newly extracted folder, and go inside "views" folder. Copy or cut the "index.html" file and paste it into the "public" folder.

4) Now, in your web brower, go to > https://cdnjs.cloudflare.com/ajax/libs/opentype.js/0.4.4/opentype.min.js
A plain text file will be displayed. In your web browser, do "File > Save as" and save the file into "CharacterMap-master\public\js" without changing the file name (which is opentype.min) and the file type (Jscript script file)

5) Close your web browser and return to the "CharacterMap-master\public" folder.  Open "index.html" with Notepad++ or Notepad 2.
In the beginning of the document, go to line 12:

`<script src="https://cdnjs.cloudflare.com/ajax/libs/opentype.js/0.4.4/opentype.min.js"></script>`

and replace it by:

`<script src="js/opentype.min.js"></script>`

then do File > Save (or CTRL+S).

6) Shut down your Internet connection, and open "index.html". And voilà, CharacterMap works offline.

**_Note**_:
Only the content of the "public" folder ("css", "fonts", "js" folders and "index.html") are needed for CharacterMap to work. So, as long as you keep these folders and this file in the same parent folder, it will works, i.e. you can delete everything else and rename/move the "public" folder at will.

**Comment by mathew-kurian** [comment]
@Ouaz Thanks!
