### ISSUE TITLE
URL is offline

### ISSUE THREAD

**Issue by marcusfelix** [mathew-kurian/CharacterMap#8]
The hosted tool is offline right now: https://bluejamesbond.github.io/CharacterMap

**Comment by Reekeyz** [comment]
I'm need to use this tool too lmao, I hope that will come back soon

**Comment by tseabra** [comment]
Hi @marcusfelix and @Reekeyz 

Just run it with docker while you're waiting . 

1. Clone repo somewhere on your computer and cd there
2. `docker run -v $(pwd):/app/ -w /app node:slim npm i`
3. `docker run -p 80:5000 -v $(pwd):/app/ -w /app node:slim node app.js`
4. Open http://localhost/

**Comment by mathew-kurian** [comment]
Should be addressed now. Thank you for the fix @tseabra. Thanks @marcusfelix for bringing up the issue.
